typo: fix
KonataDev/Konata.Core pull request #190
Opened 2022-12-07 17:59 UTC by shirok1

2022-12-07 18:01 UTC, shirok1 commented
基本都是用 typos-cli 找出来的，其中有很多 `Readed` 和 `Fille` 没敢动

2022-12-07 23:47 UTC, TheSnowfield commented
~~咦 我晚點看看, 沒發現typo這麽多過~~

2022-12-10 16:23 UTC, TheSnowfield requested changes
所有的 proto 文件屬於官方客戶端文件, 隨意修改可能會導致無法使用。已 review 的都是可以修正的。

2022-12-10 16:34 UTC, shirok1 commented
我以为这些 `.proto` 文件只是拿来参考的，因为作出这些改动前没有看到代码中有出现过同样的属性名

2022-12-10 16:42 UTC, TheSnowfield approved these changes

2022-12-10 16:42 UTC, merged

2022-12-10 16:43 UTC, TheSnowfield commented
謝謝! :3